lan = 'eth1'
#lan = 'wlan0'
wan = 'eth0'
trafic = 'True'
wwwpath = '/var/www/html/pytcrrd/'
wwwhead = '<html><head><title>PyTcRRD</title></head><body><table><tr><td>LAN - download</td><td>WAN - upload</td></tr>'
wwwfooter = '</table></body></html>'